name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          buildArgs: |
            PUBLIC_HELLO=world
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            FROM_EMAIL=${{ secrets.FROM_EMAIL }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            AXIOM_TOKEN=${{ secrets.AXIOM_TOKEN }}
            AXIOM_ORG_ID=${{ secrets.AXIOM_ORG_ID }}
            AXIOM_DATASET=${{ secrets.AXIOM_DATASET }}
            CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}
      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://caprover.aisolar.pro
          app: 'broker-your-boat'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/pampipum/boaty:latest'
